In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("./dataset/testdata2.csv")
data.head()

Unnamed: 0  ID  Gender  Race  Age_at_Release  Residence_PUMA  \
0           0   1       1     1              45              16   
1           1   2       1     1              35              16   
2           2   3       1     1              55              24   
3           3   4       1     0              40              16   
4           4   5       1     0              35              16   

   Supervision_Risk_Score_First  Supervision_Level_First  Education_Level  \
0                           3.0                        0                3   
1                           6.0                        1                1   
2                           7.0                        2                3   
3                           7.0                        2                1   
4                           4.0                        1                3   

   Dependents  ...  Violations_FailToReport  Violations_MoveWithoutPermission  \
0           3  ...                        0                                 0   
1           1  ...                        0                                 0   
2           3  ...                        0                                 1   
3           1  ...                        0                                 0   
4           3  ...                        0                                 0   

   Delinquency_Reports  Program_Attendances  Program_UnexcusedAbsences  \
0                    0                    6                          0   
1                    4                    0                          0   
2                    4                    6                          0   
3                    0                    6                          0   
4                    0                    7                          0   

   Residence_Changes  Percent_Days_Employed  Jobs_Per_Year  Employment_Exempt  \
0                  2               0.488562       0.447610                  0   
1                  2               0.425234       2.000000                  0   
2                  0               0.000000       0.000000                  0   
3                  3               1.000000       0.718996                  0   
4                  0               0.203562       0.929389                  0   

   Recidivism_Within_3years  
0                         0  
1                         1  
2                         1  
3                         0  
4                         1  

[5 rows x 44 columns]

In [5]:
data.drop(['Unnamed: 0','ID'],axis=1,inplace=True)

In [13]:
x = data.iloc[:,data.columns != "Recidivism_Within_3years"]
y = data.iloc[:,data.columns == "Recidivism_Within_3years"]

Xtrain, Xtest, Ytrain, Ytest = train_test_split(x,y,test_size=0.3)
for i in [Xtrain,Xtest,Ytrain,Ytest]:
    i.index = range(i.shape[0])

In [22]:
Ytest = pd.DataFrame(Ytest)
Ytest = Ytest.values.ravel()


In [24]:
knn = KNeighborsClassifier()
params = {"n_neighbors":[i for i in range(1,30)],"weights":["distance","uniform"],"p":[1,2]}
gcv = GridSearchCV(knn,params,scoring = "accuracy",cv = 6)
gcv.fit(Xtrain,Ytrain)


GridSearchCV(cv=6, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29],
                         'p': [1, 2], 'weights': ['distance', 'uniform']},
             scoring='accuracy')

In [25]:
gcv.best_estimator_


KNeighborsClassifier(n_neighbors=26, p=1)

In [26]:
gcv.best_score_


0.638095238095238

In [27]:
gcv.best_params_


{'n_neighbors': 26, 'p': 1, 'weights': 'uniform'}

In [28]:
y_ = gcv.predict(Xtest)
gcv.score(Xtest,Ytest)  

0.6411111111111111

In [29]:
     
pd.crosstab(index = Ytest,columns = y_,rownames=["True"],colnames=["Predict"]) 

Predict    0    1
True             
0        176  217
1        106  401

In [4]:
from models.Model_DecisionTree import decisiontree_clf_predict
import pandas as pd

data = pd.read_csv("./dataset/testdata2.csv")
if 'Unnamed: 0' in data.columns:
    data.drop(['Unnamed: 0'],inplace=True,axis=1)
temp_df = data.head(10)
x = temp_df.iloc[:,data.columns != "Recidivism_Within_3years"]
clf = decisiontree_clf_predict("./dataset/testdata2.csv")
res = pd.DataFrame(clf.predict(x))
res

0
0  0
1  1
2  1
3  0
4  1
5  0
6  1
7  1
8  1
9  1

In [1]:
import pandas as pd

data = pd.read_csv('123213/asd231')

FileNotFoundError: [Errno 2] No such file or directory: '123213/asd231'

In [1]:
# 归一化
from sklearn.preprocessing import MinMaxScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

In [2]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [4]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result  = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
result_ = scaler.fit_transform(data)
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [7]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
result =MinMaxScaler(feature_range=(5,10)).fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [11]:
# 标准化
from sklearn.preprocessing import StandardScaler
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
scaler = StandardScaler()
result = scaler.fit_transform(data)
result

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [10]:
x_std = scaler.transform(data)
print("{},{}".format(x_std.mean(),x_std.std()))

0.0,1.0


In [2]:
import pandas as pd
df = pd.read_csv('./dataset/NIJ_s_Recidivism_Datasets.csv')

In [15]:
dic = df.isnull().sum(axis=0).to_dict()
sum(dic.values())

36700